server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  admin-paths:
    paths:
      - uri: "/players"
        method: "POST"
      - uri: "/players/{1}[1-9]+[0-9]*/game"
        method: "POST"
      - uri: "/players/update/{1}[1-9]+[0-9]*"
        method: "PUT"
      - uri: "/players/update/{1}[1-9]+[0-9]*"
        method: "POST"
      - uri: "/players/update/rate/{1}[1-9]+[0-9]*"
        method: "POST"
      - uri: "/players/{1}[1-9]+[0-9]*/games"
        method: "DELETE"
      - uri: "/players"
        method: "GET"
      - uri: "/games"
        method: "GET"
      - uri: "/games/{1}[1-9]+[0-9]*"
        method: "GET"
      - uri: "/players/ranking"
        method: "GET"
      - uri: "/players/ranking/loser"
        method: "GET"
      - uri: "/players/{1}[1-9]+[0-9]*/games"
        method: "GET"

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: auth
      auto-index-creation: true

management:
  tracing:
    sampling:
      probability: 1.0