server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: player-service
          uri: lb://player-service
          predicates:
            - Path=/players/**
        - id: game-service
          uri: lb://game-service
          predicates:
            - Path=/games/**

management:
  tracing:
    sampling:
      probability: 1.0