server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/plopezgit/Sprint5_T1_SpringBoot_Dice_Roller_Microservices
          search-paths: config-data

  application:
    name: config-service

